use anyhow::{Context, Result};
use aya::maps::HashMap;
use aya::Ebpf;
use tracing::info;

/// Populate the PID_FILTER BPF map with our own PID.
///
/// This ensures all probes skip events generated by jalki itself,
/// preventing feedback loops (e.g., jalki's gRPC emit causing tcp_connect events).
pub fn populate_pid_filter(ebpf: &mut Ebpf) -> Result<()> {
    let mut map: HashMap<_, u32, u8> = ebpf
        .map_mut("PID_FILTER")
        .ok_or_else(|| anyhow::anyhow!("PID_FILTER map not found"))?
        .try_into()
        .context("PID_FILTER is not a HashMap")?;

    let pid = std::process::id();
    map.insert(pid, 1, 0)
        .context("failed to insert self PID into filter")?;

    info!(pid, "self-filter: inserted own PID");
    Ok(())
}

/// Add additional PIDs to the filter (e.g., child processes).
pub fn add_pid(ebpf: &mut Ebpf, pid: u32) -> Result<()> {
    let mut map: HashMap<_, u32, u8> = ebpf
        .map_mut("PID_FILTER")
        .ok_or_else(|| anyhow::anyhow!("PID_FILTER map not found"))?
        .try_into()
        .context("PID_FILTER is not a HashMap")?;

    map.insert(pid, 1, 0)
        .with_context(|| format!("failed to insert PID {pid} into filter"))?;

    info!(pid, "self-filter: added PID");
    Ok(())
}
