use super::CodegenTarget;

pub struct PythonTarget;

impl CodegenTarget for PythonTarget {
    fn language(&self) -> &'static str {
        "python"
    }

    fn types_filename(&self) -> &'static str {
        "types.py"
    }

    fn protocol_filename(&self) -> &'static str {
        "protocol.py"
    }

    fn generate_types(&self) -> String {
        format!(
            r#"# GENERATED by jalki-sdk-meta v{version}. DO NOT EDIT.
#
# Canonical type definitions for the jälki Python SDK.
# Change jalki-sdk-meta/src/types.rs, regenerate, commit.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum, StrEnum
from typing import Optional


class Severity(IntEnum):
    INFO = 0
    WARNING = 1
    ERROR = 2
    CRITICAL = 3


class Outcome(IntEnum):
    SUCCESS = 0
    FAILURE = 1
    UNKNOWN = 2


class Proto(IntEnum):
    TCP = 0
    UDP = 1


class Attachment(StrEnum):
    # Lowercase string values match Rust's serde rename_all = "lowercase".
    FENTRY = "fentry"
    FEXIT = "fexit"


@dataclass
class NetData:
    """Network data — combined ip:port strings for minimal token cost."""

    src: str
    dst: str
    proto: Proto


@dataclass
class ProcData:
    """Process data."""

    pid: int
    cmd: str


@dataclass
class Interpretation:
    """KB interpretation of an event."""

    conclusion: str
    action: str


@dataclass
class EventFilter:
    """Filter applied server-side — events not matching never cross the wire."""

    src_ip: Optional[str] = None
    dst_ip: Optional[str] = None
    src_port: Optional[int] = None
    dst_port: Optional[int] = None
    pid: Optional[int] = None
    command: Optional[str] = None
    last_seconds: Optional[int] = None
    limit: Optional[int] = None


@dataclass
class FieldInfo:
    """A field in a probe's event."""

    name: str
    meaning: str
    important: bool


@dataclass
class ProbeMatch:
    """Result from find() — a matching probe from the knowledge base."""

    function: str
    attachment: str
    event_type: str
    why: str
    fields: list[FieldInfo]
    combine_with: list[str]


@dataclass
class ProbeHandle:
    """Handle to a deployed probe, used for streaming."""

    probe_id: str
    function: str


@dataclass
class Event:
    """Compact SDK event — NOT a full FALSE Protocol Occurrence."""

    id: str
    ts: int
    probe: str
    severity: Severity
    outcome: Outcome
    net: Optional[NetData] = None
    proc: Optional[ProcData] = None
    labels: Optional[dict[str, str]] = None
    interp: Optional[Interpretation] = None
    _client: object = field(default=None, repr=False)

    async def full(self) -> dict:
        """Lazy fetch of full FALSE Protocol Occurrence. Call only when needed."""
        if self._client is None:
            raise RuntimeError("no client — event was not received via stream")
        return await self._client._fetch_full(self.id)


@dataclass
class AskResult:
    """Result from ask() — interpretation + collected events."""

    interpretation: str
    severity: Severity
    action: str
    events: list[Event]
    probes_used: list[str]
    kb_only: bool = False


@dataclass
class AskOptions:
    """Options for ask()."""

    collect_seconds: Optional[int] = None
    max_events: Optional[int] = None
    filter: Optional[EventFilter] = None


@dataclass
class DeployOptions:
    """Options for deploy()."""

    sample_rate: Optional[float] = None
    filter: Optional[EventFilter] = None


@dataclass
class StreamOptions:
    """Options for stream()."""

    filter: Optional[EventFilter] = None
    interpreted: Optional[bool] = None
"#,
            version = env!("CARGO_PKG_VERSION")
        )
    }

    fn generate_protocol(&self) -> String {
        format!(
            r#"# GENERATED by jalki-sdk-meta v{version}. DO NOT EDIT.
#
# Wire protocol constants for the jälki Python SDK.
# Change jalki-sdk-meta/src/protocol.rs, regenerate, commit.

from enum import IntEnum


class MsgType(IntEnum):
    """Wire message types."""

    REQUEST = 0x01
    RESPONSE = 0x02
    STREAM_START = 0x03
    STREAM_EVENT = 0x04
    STREAM_END = 0x05
    ERROR = 0x06
    PING = 0x07
    PONG = 0x08


class Method(IntEnum):
    """RPC methods."""

    FIND = 0x01
    DEPLOY = 0x02
    SUBSCRIBE = 0x03
    UNSUBSCRIBE = 0x04
    STATUS = 0x05
    ASK = 0x06


class Flags:
    """Frame flags."""

    COMPRESSED: int = 0x01
    INTERPRETED: int = 0x02
    FULL_PROTOCOL: int = 0x04


# Frame layout:
# [frame_len: u32 big-endian][msg_type: u8][flags: u8][payload: msgpack]
# frame_len includes msg_type and flags bytes.
FRAME_HEADER_LEN: int = 6  # 4 (len) + 1 (type) + 1 (flags)
FRAME_MAX_LEN: int = 1024 * 1024  # 1MB

# STREAM_EVENT wire positions (positional MessagePack array).
# No field names on wire — SDK maps positions to struct fields.
POS_ID: int = 0  # str (ULID)
POS_PROBE_IDX: int = 1  # u8 — index into probe name table from STREAM_START
POS_TS: int = 2  # u64 nanoseconds
POS_SEVERITY: int = 3  # u8 (Severity enum)
POS_OUTCOME: int = 4  # u8 (Outcome enum)
POS_NET_SRC: int = 5  # str|nil "ip:port"
POS_NET_DST: int = 6  # str|nil "ip:port"
POS_PROTO: int = 7  # u8|nil (Proto enum)
POS_PID: int = 8  # u32|nil
POS_CMD: int = 9  # str|nil
POS_LABELS: int = 10  # map|nil
POS_INTERP: int = 11  # [str, str]|nil — [conclusion, action]

# Timing constants.
KEEPALIVE_INTERVAL_SECS: int = 30
KEEPALIVE_TIMEOUT_SECS: int = 5
REQUEST_TIMEOUT_SECS: int = 30
RECONNECT_BASE_MS: int = 100
RECONNECT_MAX_MS: int = 5000
"#,
            version = env!("CARGO_PKG_VERSION")
        )
    }
}
