# GENERATED by jalki-sdk-meta v0.1.0. DO NOT EDIT.
#
# Wire protocol constants for the jälki Python SDK.
# Change jalki-sdk-meta/src/protocol.rs, regenerate, commit.

from enum import IntEnum


class MsgType(IntEnum):
    """Wire message types."""

    REQUEST = 0x01
    RESPONSE = 0x02
    STREAM_START = 0x03
    STREAM_EVENT = 0x04
    STREAM_END = 0x05
    ERROR = 0x06
    PING = 0x07
    PONG = 0x08


class Method(IntEnum):
    """RPC methods."""

    FIND = 0x01
    DEPLOY = 0x02
    SUBSCRIBE = 0x03
    UNSUBSCRIBE = 0x04
    STATUS = 0x05
    ASK = 0x06


class Flags:
    """Frame flags."""

    COMPRESSED: int = 0x01
    INTERPRETED: int = 0x02
    FULL_PROTOCOL: int = 0x04


# Frame layout:
# [frame_len: u32 big-endian][msg_type: u8][flags: u8][payload: msgpack]
# frame_len includes msg_type and flags bytes.
FRAME_HEADER_LEN: int = 6  # 4 (len) + 1 (type) + 1 (flags)
FRAME_MAX_LEN: int = 1024 * 1024  # 1MB

# STREAM_EVENT wire positions (positional MessagePack array).
# No field names on wire — SDK maps positions to struct fields.
POS_ID: int = 0  # str (ULID)
POS_PROBE_IDX: int = 1  # u8 — index into probe name table from STREAM_START
POS_TS: int = 2  # u64 nanoseconds
POS_SEVERITY: int = 3  # u8 (Severity enum)
POS_OUTCOME: int = 4  # u8 (Outcome enum)
POS_NET_SRC: int = 5  # str|nil "ip:port"
POS_NET_DST: int = 6  # str|nil "ip:port"
POS_PROTO: int = 7  # u8|nil (Proto enum)
POS_PID: int = 8  # u32|nil
POS_CMD: int = 9  # str|nil
POS_LABELS: int = 10  # map|nil
POS_INTERP: int = 11  # [str, str]|nil — [conclusion, action]

# Timing constants.
KEEPALIVE_INTERVAL_SECS: int = 30
KEEPALIVE_TIMEOUT_SECS: int = 5
REQUEST_TIMEOUT_SECS: int = 30
RECONNECT_BASE_MS: int = 100
RECONNECT_MAX_MS: int = 5000
