# GENERATED by jalki-sdk-meta v0.1.0. DO NOT EDIT.
#
# Canonical type definitions for the jälki Python SDK.
# Change jalki-sdk-meta/src/types.rs, regenerate, commit.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum
from typing import Optional


class Severity(IntEnum):
    INFO = 0
    WARNING = 1
    ERROR = 2
    CRITICAL = 3


class Outcome(IntEnum):
    SUCCESS = 0
    FAILURE = 1
    UNKNOWN = 2


class Proto(IntEnum):
    TCP = 0
    UDP = 1


class Attachment(IntEnum):
    FENTRY = 0
    FEXIT = 1


@dataclass
class NetData:
    """Network data — combined ip:port strings for minimal token cost."""

    src: str
    dst: str
    proto: Proto


@dataclass
class ProcData:
    """Process data."""

    pid: int
    cmd: str


@dataclass
class Interpretation:
    """KB interpretation of an event."""

    conclusion: str
    action: str


@dataclass
class EventFilter:
    """Filter applied server-side — events not matching never cross the wire."""

    src_ip: Optional[str] = None
    dst_ip: Optional[str] = None
    src_port: Optional[int] = None
    dst_port: Optional[int] = None
    pid: Optional[int] = None
    command: Optional[str] = None
    last_seconds: Optional[int] = None
    limit: Optional[int] = None


@dataclass
class FieldInfo:
    """A field in a probe's event."""

    name: str
    meaning: str
    important: bool


@dataclass
class ProbeMatch:
    """Result from find() — a matching probe from the knowledge base."""

    function: str
    attachment: str
    event_type: str
    why: str
    fields: list[FieldInfo]
    combine_with: list[str]


@dataclass
class ProbeHandle:
    """Handle to a deployed probe, used for streaming."""

    probe_id: str
    function: str


@dataclass
class Event:
    """Compact SDK event — NOT a full FALSE Protocol Occurrence."""

    id: str
    ts: int
    probe: str
    severity: Severity
    outcome: Outcome
    net: Optional[NetData] = None
    proc: Optional[ProcData] = None
    labels: Optional[dict[str, str]] = None
    interp: Optional[Interpretation] = None
    _client: object = field(default=None, repr=False)

    async def full(self) -> dict:
        """Lazy fetch of full FALSE Protocol Occurrence. Call only when needed."""
        if self._client is None:
            raise RuntimeError("no client — event was not received via stream")
        return await self._client._fetch_full(self.id)


@dataclass
class AskResult:
    """Result from ask() — interpretation + collected events."""

    interpretation: str
    severity: Severity
    action: str
    events: list[Event]
    probes_used: list[str]
    kb_only: bool = False


@dataclass
class AskOptions:
    """Options for ask()."""

    collect_seconds: Optional[int] = None
    max_events: Optional[int] = None
    filter: Optional[EventFilter] = None


@dataclass
class DeployOptions:
    """Options for deploy()."""

    sample_rate: Optional[float] = None
    filter: Optional[EventFilter] = None


@dataclass
class StreamOptions:
    """Options for stream()."""

    filter: Optional[EventFilter] = None
    interpreted: Optional[bool] = None
