// This file is @generated by prost-build.
/// One batch = one (source_key, provider, namespace) from one adapter/node.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProviderEvidenceBatch {
    /// e.g. "tetragon"        -> ProviderEvidence.source_key
    #[prost(string, tag = "1")]
    pub source_key: ::prost::alloc::string::String,
    /// e.g. "tetragon"        -> ProviderEvidence.provider
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    /// e.g. "vartio-tetragon" (Ahti adapter namespace)
    #[prost(string, tag = "3")]
    pub namespace: ::prost::alloc::string::String,
    /// adapter-generated; response/log correlation (-> delivery_id)
    #[prost(string, tag = "4")]
    pub batch_id: ::prost::alloc::string::String,
    /// -> ProviderEvidence.source_context.adapter_id
    #[prost(string, tag = "5")]
    pub adapter_id: ::prost::alloc::string::String,
    /// -> source_context.cluster_id (+ idempotency scope)
    #[prost(string, tag = "6")]
    pub cluster_id: ::prost::alloc::string::String,
    /// -> source_context.node_id    (+ idempotency scope)
    #[prost(string, tag = "7")]
    pub node_id: ::prost::alloc::string::String,
    /// adapter send time; server stamps received_at
    #[prost(message, optional, tag = "8")]
    pub ingested_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "9")]
    pub items: ::prost::alloc::vec::Vec<ProviderEvidenceItem>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProviderEvidenceItem {
    /// Source-scoped execution identity: source_key + cluster_id + node_id + exec_id
    /// (or a canonical globally-unique equivalent). Vartio dedups on this at ingress;
    /// the importer derives the durable Ahti logical_key from the normalized event.
    #[prost(string, tag = "1")]
    pub idempotency_key: ::prost::alloc::string::String,
    /// e.g. "tetragon.process_exec"
    #[prost(string, tag = "2")]
    pub occurrence_type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub observed_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Provider-native record body as UTF-8 JSON bytes. MUST be source-redacted at
    /// the node: process.arguments stripped and replaced with argv_hash. Raw argv
    /// MUST NOT cross the wire.
    #[prost(bytes = "vec", tag = "4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Optional context as UTF-8 JSON object bytes. HARD CONSTRAINT: Vartio's
    /// ProviderEvidence validation rejects the whole item if metadata or
    /// trust_context contains a key matching authorization / *token* / *secret* /
    /// *signature* / raw_body / body. Strip secrets at the adapter.
    #[prost(bytes = "vec", tag = "5")]
    pub metadata: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub trust_context: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemResult {
    #[prost(string, tag = "1")]
    pub idempotency_key: ::prost::alloc::string::String,
    #[prost(enumeration = "ItemStatus", tag = "2")]
    pub status: i32,
    /// set when status = ITEM_STATUS_REJECTED
    #[prost(enumeration = "RejectReason", tag = "3")]
    pub reason: i32,
    /// per-item: true for transient reasons
    #[prost(bool, tag = "4")]
    pub retryable: bool,
    /// human-readable; no secrets / no raw payload
    #[prost(string, tag = "5")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReasonSummary {
    #[prost(enumeration = "RejectReason", tag = "1")]
    pub reason: i32,
    #[prost(uint32, tag = "2")]
    pub count: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiveBatchResponse {
    #[prost(string, tag = "1")]
    pub batch_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub accepted_count: u32,
    #[prost(uint32, tag = "3")]
    pub duplicate_count: u32,
    #[prost(uint32, tag = "4")]
    pub rejected_count: u32,
    /// MAY be omitted for large all-accepted batches
    #[prost(message, repeated, tag = "5")]
    pub items: ::prost::alloc::vec::Vec<ItemResult>,
    #[prost(message, repeated, tag = "6")]
    pub error_summaries: ::prost::alloc::vec::Vec<ReasonSummary>,
    /// Batch-level retry signal: true if ANY item failed with a retryable reason.
    /// The emitter returns Err and retries the whole batch; accepted/duplicate items
    /// replay safely via idempotency_key.
    #[prost(bool, tag = "7")]
    pub retryable: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ItemStatus {
    Unspecified = 0,
    Accepted = 1,
    /// idempotent no-op; never an error
    Duplicate = 2,
    Rejected = 3,
}
impl ItemStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ITEM_STATUS_UNSPECIFIED",
            Self::Accepted => "ITEM_STATUS_ACCEPTED",
            Self::Duplicate => "ITEM_STATUS_DUPLICATE",
            Self::Rejected => "ITEM_STATUS_REJECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ITEM_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "ITEM_STATUS_ACCEPTED" => Some(Self::Accepted),
            "ITEM_STATUS_DUPLICATE" => Some(Self::Duplicate),
            "ITEM_STATUS_REJECTED" => Some(Self::Rejected),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RejectReason {
    Unspecified = 0,
    /// permanent — do not retry the item
    ///
    /// authn/trust failure
    Unauthorized = 1,
    UntrustedSource = 2,
    MalformedPayload = 3,
    /// unknown occurrence_type / namespace
    UnsupportedEvent = 4,
    /// structural / missing field / secret-key rejected
    ValidationFailed = 5,
    /// retryable — transient
    ///
    /// Ahti append/transport unavailable
    AppendFailed = 6,
    ReadbackFailed = 7,
    Internal = 8,
}
impl RejectReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REJECT_REASON_UNSPECIFIED",
            Self::Unauthorized => "REJECT_REASON_UNAUTHORIZED",
            Self::UntrustedSource => "REJECT_REASON_UNTRUSTED_SOURCE",
            Self::MalformedPayload => "REJECT_REASON_MALFORMED_PAYLOAD",
            Self::UnsupportedEvent => "REJECT_REASON_UNSUPPORTED_EVENT",
            Self::ValidationFailed => "REJECT_REASON_VALIDATION_FAILED",
            Self::AppendFailed => "REJECT_REASON_APPEND_FAILED",
            Self::ReadbackFailed => "REJECT_REASON_READBACK_FAILED",
            Self::Internal => "REJECT_REASON_INTERNAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REJECT_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "REJECT_REASON_UNAUTHORIZED" => Some(Self::Unauthorized),
            "REJECT_REASON_UNTRUSTED_SOURCE" => Some(Self::UntrustedSource),
            "REJECT_REASON_MALFORMED_PAYLOAD" => Some(Self::MalformedPayload),
            "REJECT_REASON_UNSUPPORTED_EVENT" => Some(Self::UnsupportedEvent),
            "REJECT_REASON_VALIDATION_FAILED" => Some(Self::ValidationFailed),
            "REJECT_REASON_APPEND_FAILED" => Some(Self::AppendFailed),
            "REJECT_REASON_READBACK_FAILED" => Some(Self::ReadbackFailed),
            "REJECT_REASON_INTERNAL" => Some(Self::Internal),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod source_ingress_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct SourceIngressClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SourceIngressClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SourceIngressClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SourceIngressClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SourceIngressClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Bursty source/runtime evidence in batches. All-or-retry: any retryable item
        /// failure makes the whole batch retryable; accepted and duplicate items replay
        /// safely because per-item idempotency is stable. This is retry-with-idempotency,
        /// not transactional rollback — some items may be accepted before a transient
        /// failure, and return DUPLICATE on the whole-batch retry.
        pub async fn receive_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::ProviderEvidenceBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ReceiveBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/vartio.source_ingress.v1.SourceIngress/ReceiveBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "vartio.source_ingress.v1.SourceIngress",
                        "ReceiveBatch",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod source_ingress_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SourceIngressServer.
    #[async_trait]
    pub trait SourceIngress: std::marker::Send + std::marker::Sync + 'static {
        /// Bursty source/runtime evidence in batches. All-or-retry: any retryable item
        /// failure makes the whole batch retryable; accepted and duplicate items replay
        /// safely because per-item idempotency is stable. This is retry-with-idempotency,
        /// not transactional rollback — some items may be accepted before a transient
        /// failure, and return DUPLICATE on the whole-batch retry.
        async fn receive_batch(
            &self,
            request: tonic::Request<super::ProviderEvidenceBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ReceiveBatchResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct SourceIngressServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SourceIngressServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SourceIngressServer<T>
    where
        T: SourceIngress,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/vartio.source_ingress.v1.SourceIngress/ReceiveBatch" => {
                    #[allow(non_camel_case_types)]
                    struct ReceiveBatchSvc<T: SourceIngress>(pub Arc<T>);
                    impl<
                        T: SourceIngress,
                    > tonic::server::UnaryService<super::ProviderEvidenceBatch>
                    for ReceiveBatchSvc<T> {
                        type Response = super::ReceiveBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProviderEvidenceBatch>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SourceIngress>::receive_batch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReceiveBatchSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SourceIngressServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "vartio.source_ingress.v1.SourceIngress";
    impl<T> tonic::server::NamedService for SourceIngressServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
